import type { ClosureFailureCode } from "./types.js";

export const PROTOCOL_REASON_CODES = [
  "MALFORMED_SCHEMA",
  "HASH_MISMATCH",
  "INVALID_SIGNATURE",
  "INVALID_LEDGER_SIGNATURE",
  "UNKNOWN_KEY",
  "STALE_TRUST_HEAD",
  "KEY_REVOKED",
  "MANDATE_EXPIRED",
  "MANDATE_REVOKED",
  "OUT_OF_SCOPE",
  "POLICY_DENY",
  "STEP_UP_REQUIRED",
  "SEPARATION_FAILURE",
  "INVALID_STATE_TRANSITION",
  "CAPSULE_EXPIRED",
  "CAPSULE_REUSED",
  "IDEMPOTENCY_CONFLICT",
  "CLOCK_ROLLBACK",
  "EXECUTION_UNKNOWN",
  "EXECUTOR_REJECTED",
  "UNTRUSTED_EXECUTOR",
  "EXTERNAL_EFFECT_UNVERIFIED",
  "CLOSURE_MISMATCH",
  "INCOMPLETE_LEDGER_RANGE",
  "INCOMPLETE_CONSUMPTION_RANGE",
  "PROOF_LIMIT_EXCEEDED",
  "SERVICE_BUSY",
  "UNSUPPORTED_VERSION",
] as const;

export type ProtocolReasonCode = (typeof PROTOCOL_REASON_CODES)[number];

export const CLOSURE_FAILURE_CODES = [
  "TRUST_STORE_SCHEMA_INVALID",
  "PROOF_SCHEMA_INVALID",
  "TRUST_ROOT_NOT_TRUSTED",
  "TRUST_MANIFEST_BINDING_INVALID",
  "TRUST_MANIFEST_SIGNATURE_INVALID",
  "MANIFEST_PIN_MISMATCH",
  "ASSURANCE_PROFILE_MISMATCH",
  "AUTHORITY_BINDING_INVALID",
  "SIGNATURE_ORDER_INVALID",
  "SIGNATURE_INVALID",
  "MANDATE_SCOPE_INVALID",
  "AUTHORIZATION_TIME_INVALID",
  "OBJECT_HASH_LINK_INVALID",
  "POLICY_UNSUPPORTED",
  "INTERPRETER_UNSUPPORTED",
  "DECISION_REPLAY_MISMATCH",
  "DECISION_NOT_ALLOWED",
  "EFFECT_MISMATCH",
  "CAPSULE_LINK_INVALID",
  "CAPSULE_TIME_INVALID",
  "CONSUMPTION_CARDINALITY_INVALID",
  "CONSUMPTION_LINK_INVALID",
  "RECEIPT_LINK_INVALID",
  "LEDGER_OBSERVATION_INVALID",
  "STATE_PATH_INVALID",
  "CLOSURE_TIME_INVALID",
  "SEPARATION_FAILURE",
  "STEP_UP_MISSING",
  "MANDATE_REVOKED",
  "SIDE_EFFECT_PRESENT",
  "STALE_TRUST_HEAD",
  "KEY_REVOKED",
  "UNKNOWN_KEY",
  "PROOF_LIMIT_EXCEEDED",
  "INTERNAL_VERIFICATION_ERROR",
] as const satisfies readonly ClosureFailureCode[];

export const HTTP_STATUS_BY_REASON = {
  MALFORMED_SCHEMA: 400,
  HASH_MISMATCH: 400,
  INVALID_SIGNATURE: 400,
  INVALID_LEDGER_SIGNATURE: 400,
  UNKNOWN_KEY: 422,
  STALE_TRUST_HEAD: 422,
  KEY_REVOKED: 422,
  MANDATE_EXPIRED: 422,
  MANDATE_REVOKED: 422,
  OUT_OF_SCOPE: 422,
  POLICY_DENY: 422,
  STEP_UP_REQUIRED: 202,
  SEPARATION_FAILURE: 422,
  INVALID_STATE_TRANSITION: 422,
  CAPSULE_EXPIRED: 422,
  CAPSULE_REUSED: 409,
  IDEMPOTENCY_CONFLICT: 409,
  CLOCK_ROLLBACK: 422,
  EXECUTION_UNKNOWN: 202,
  EXECUTOR_REJECTED: 422,
  UNTRUSTED_EXECUTOR: 422,
  EXTERNAL_EFFECT_UNVERIFIED: 422,
  CLOSURE_MISMATCH: 422,
  INCOMPLETE_LEDGER_RANGE: 400,
  INCOMPLETE_CONSUMPTION_RANGE: 400,
  PROOF_LIMIT_EXCEEDED: 400,
  SERVICE_BUSY: 503,
  UNSUPPORTED_VERSION: 422,
} as const satisfies Record<ProtocolReasonCode, number>;

export const CLI_EXIT_BY_REASON = {
  MALFORMED_SCHEMA: 2,
  HASH_MISMATCH: 2,
  INVALID_SIGNATURE: 2,
  INVALID_LEDGER_SIGNATURE: 2,
  UNKNOWN_KEY: 2,
  STALE_TRUST_HEAD: 2,
  KEY_REVOKED: 2,
  MANDATE_EXPIRED: 2,
  MANDATE_REVOKED: 2,
  OUT_OF_SCOPE: 2,
  POLICY_DENY: 2,
  STEP_UP_REQUIRED: 2,
  SEPARATION_FAILURE: 2,
  INVALID_STATE_TRANSITION: 2,
  CAPSULE_EXPIRED: 2,
  CAPSULE_REUSED: 2,
  IDEMPOTENCY_CONFLICT: 2,
  CLOCK_ROLLBACK: 2,
  EXECUTION_UNKNOWN: 2,
  EXECUTOR_REJECTED: 2,
  UNTRUSTED_EXECUTOR: 2,
  EXTERNAL_EFFECT_UNVERIFIED: 2,
  CLOSURE_MISMATCH: 2,
  INCOMPLETE_LEDGER_RANGE: 2,
  INCOMPLETE_CONSUMPTION_RANGE: 2,
  PROOF_LIMIT_EXCEEDED: 2,
  SERVICE_BUSY: 2,
  UNSUPPORTED_VERSION: 2,
} as const satisfies Record<ProtocolReasonCode, 2>;

export const FAILURE_CODE_TO_REASON = {
  TRUST_STORE_SCHEMA_INVALID: "MALFORMED_SCHEMA",
  PROOF_SCHEMA_INVALID: "MALFORMED_SCHEMA",
  TRUST_ROOT_NOT_TRUSTED: "UNKNOWN_KEY",
  TRUST_MANIFEST_BINDING_INVALID: "MALFORMED_SCHEMA",
  TRUST_MANIFEST_SIGNATURE_INVALID: "INVALID_SIGNATURE",
  MANIFEST_PIN_MISMATCH: "HASH_MISMATCH",
  ASSURANCE_PROFILE_MISMATCH: "UNSUPPORTED_VERSION",
  AUTHORITY_BINDING_INVALID: "UNKNOWN_KEY",
  SIGNATURE_ORDER_INVALID: "INVALID_SIGNATURE",
  SIGNATURE_INVALID: "INVALID_SIGNATURE",
  MANDATE_SCOPE_INVALID: "OUT_OF_SCOPE",
  AUTHORIZATION_TIME_INVALID: "MANDATE_EXPIRED",
  OBJECT_HASH_LINK_INVALID: "HASH_MISMATCH",
  POLICY_UNSUPPORTED: "UNSUPPORTED_VERSION",
  INTERPRETER_UNSUPPORTED: "UNSUPPORTED_VERSION",
  DECISION_REPLAY_MISMATCH: "CLOSURE_MISMATCH",
  DECISION_NOT_ALLOWED: "POLICY_DENY",
  EFFECT_MISMATCH: "CLOSURE_MISMATCH",
  CAPSULE_LINK_INVALID: "HASH_MISMATCH",
  CAPSULE_TIME_INVALID: "CAPSULE_EXPIRED",
  CONSUMPTION_CARDINALITY_INVALID: "INCOMPLETE_CONSUMPTION_RANGE",
  CONSUMPTION_LINK_INVALID: "INCOMPLETE_CONSUMPTION_RANGE",
  RECEIPT_LINK_INVALID: "CLOSURE_MISMATCH",
  LEDGER_OBSERVATION_INVALID: "INCOMPLETE_LEDGER_RANGE",
  STATE_PATH_INVALID: "INVALID_STATE_TRANSITION",
  CLOSURE_TIME_INVALID: "INVALID_STATE_TRANSITION",
  SEPARATION_FAILURE: "SEPARATION_FAILURE",
  STEP_UP_MISSING: "STEP_UP_REQUIRED",
  MANDATE_REVOKED: "MANDATE_REVOKED",
  SIDE_EFFECT_PRESENT: "CLOSURE_MISMATCH",
  STALE_TRUST_HEAD: "STALE_TRUST_HEAD",
  KEY_REVOKED: "KEY_REVOKED",
  UNKNOWN_KEY: "UNKNOWN_KEY",
  PROOF_LIMIT_EXCEEDED: "PROOF_LIMIT_EXCEEDED",
  INTERNAL_VERIFICATION_ERROR: "MALFORMED_SCHEMA",
} as const satisfies Record<ClosureFailureCode, ProtocolReasonCode>;

export const EVALUATOR_CODE_TO_REASON = {
  SOURCE_ACCOUNT_NOT_OPEN: "POLICY_DENY",
  DESTINATION_ACCOUNT_NOT_OPEN: "POLICY_DENY",
  SENDER_OWNERSHIP_MISMATCH: "POLICY_DENY",
  INSUFFICIENT_SPENDABLE_FUNDS: "POLICY_DENY",
  DAILY_CAP_EXCEEDED: "POLICY_DENY",
  CROSS_CUSTOMER_TRANSFER: "OUT_OF_SCOPE",
  STEP_UP_REQUIRED: "STEP_UP_REQUIRED",
} as const;

export function isProtocolReasonCode(value: string): value is ProtocolReasonCode {
  return (PROTOCOL_REASON_CODES as readonly string[]).includes(value);
}

export function toProtocolReasonCode(
  code: ClosureFailureCode | string,
  path = "",
): ProtocolReasonCode | undefined {
  if (isProtocolReasonCode(code)) return code;
  if (code === "SIGNATURE_INVALID" && path.includes("ledger")) {
    return "INVALID_LEDGER_SIGNATURE";
  }
  if (code in FAILURE_CODE_TO_REASON) {
    return FAILURE_CODE_TO_REASON[code as ClosureFailureCode];
  }
  if (code in EVALUATOR_CODE_TO_REASON) {
    return EVALUATOR_CODE_TO_REASON[code as keyof typeof EVALUATOR_CODE_TO_REASON];
  }
  return undefined;
}

export function httpStatusForReason(code: ProtocolReasonCode): number {
  return HTTP_STATUS_BY_REASON[code];
}

export function cliExitForReason(code: ProtocolReasonCode): number {
  return CLI_EXIT_BY_REASON[code];
}
